version: "3.9"

services:
  rag-service:
    build:
      context: ./rag_service
      dockerfile: Dockerfile.rag
    # container_name is optional, can be removed for better scalability
    container_name: rag-service
    ports:
      - "8080:8080"
    env_file:
      - ./rag_service/.env
    volumes:
      - ./rag_service/data:/app/data
      - ./rag_service/chroma_store:/app/chroma_store
    networks:
      - emotion
    # It's good practice to tell your RAG service where the vLLM API is
    environment:
      - MODEL_SERVICE_URL=http://vllm-qwen:8000
      - CHARACTER_QUOTES_PATH=data/character_quotes.txt
      - BACKGROUND=data/background.txt

networks:
  emotion:
    external: true