version: "3.9"

services:
  rag-service:
    build:
      context: ./rag_service
      dockerfile: Dockerfile.rag
    # container_name is optional, can be removed for better scalability
    container_name: rag-service
    ports:
      - "8080:8080"
    env_file:
      - ./rag_service/.env
    volumes:
      - ./rag_service/data:/app/data
      - ./rag_service/chroma_store:/app/chroma_store
    environment:
      - CHARACTER_QUOTES_PATH=data/character_quotes.txt
      - BACKGROUND=data/background.txt
      - DASHSCOPE_API_KEY=${DASHSCOPE_API_KEY}